name: Update version and create release PR
run-name: Update Version
on:
  workflow_dispatch:
    inputs:
      type:
        description: 'Type of release'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Build Assets
        id: build
        run: |
          npm install
          npm run build
      - name: Run Unit Tests
        id: test
        if: steps.build.outcome == 'success'
        run: npm run test
      - name: Update Version
        id: update_version
        run: |
          echo "version=$(npm version ${{ github.event.inputs.type }} --no-git-tag-version)" >> $GITHUB_OUTPUT
      - name: Update Changelog & README
        id: update_changelog
        run: |
          sed -i 's/Unreleased/${{ steps.update_version.outputs.version }}/g' CHANGELOG.md
          sed -i 's/"alt=Version .*/alt="Version: ${{ steps.update_version.outputs.version }}">/g' README.md
      - name: Create Release PR
        id: create_pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: release/${{ steps.update_version.outputs.version }}
          title: "Release ${{ steps.update_version.outputs.version }}"
          body: "Release ${{ steps.update_version.outputs.version }}"
          base: main
